routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*-----------------index-----------------------*/
Auth::routes(['verify'=>true]);
Route::match(['get', 'post'], 'register', function(){
    return redirect('/');
});

Route::get('kirim-email',[
    'uses' => 'TestController@kirim',
    'as'    => 'kirim'
]);

Route::get('/home',[
    'uses'  => 'HomeController@index',
    'as'    => 'home' ,
    'middleware' => ['role:superadmin|keuangan|kepegawaian|humas|renpro|desain|tarif|lala|fasilitas|bimus']
]);

Route::get('/verifikasi-sukses','HomeController@verifikasi');
/*--------------------end of index-------------*/

/*-------------------backend-------------------*/
Route::group(['prefix'=>'admin', 'middleware'=>['auth'],'as'=>'admin.'], function(){
    Route::group(['middleware'=>['role:superadmin|humas']], function(){
        Route::resource('kategori-berita', 'Backend\KategoriBeritaController');
        Route::resource('kategori-foto', 'Backend\KategoriFotoController');
        Route::resource('kategori-video', 'Backend\KategoriVideoController');
        Route::resource('kategori-hukum', 'Backend\KategoriHukumController');
        Route::resource('jenis-usaha', 'Backend\JenisUsahaController');
        Route::resource('jenis-pelayanan', 'Backend\JenisPelayananController');
        Route::resource('jenis-informasi', 'Backend\JenisInformasiController');
        Route::resource('jenis-laporan', 'Backend\JenisLaporanController');
        Route::resource('tampilan-depan', 'Backend\TampilanDepanController');
        Route::resource('berita', 'Backend\BeritaController');
        Route::put('berita/restore/{id}',[
            'uses' => 'Backend\BeritaController@restore',
            'as' => 'berita.restore'
        ]);
        Route::delete('berita/force-destroy/{id}',[
            'uses' => 'Backend\BeritaController@forceDestroy',
            'as' => 'berita.force-destroy'
        ]);
        Route::resource('link-terkait', 'Backend\LinkTerkaitController');
        Route::put('link-terkait/restore/{id}',[
            'uses' => 'Backend\LinkTerkaitController@restore',
            'as' => 'link-terkait.restore'
        ]);
        Route::delete('link-terkait/force-destroy/{id}',[
            'uses' => 'Backend\LinkTerkaitController@forceDestroy',
            'as' => 'link-terkait.force-destroy'
        ]);
        // Route::resource('reformasi-birokrasi', 'Backend\ReformasiBirokrasiController');
        // Route::put('reformasi-birokrasi/restore/{id}',[
        //     'uses' => 'Backend\ReformasiBirokrasiController@restore',
        //     'as' => 'reformasi-birokrasi.restore'
        // ]);
        // Route::delete('reformasi-birokrasi/force-destroy/{id}',[
        //     'uses' => 'Backend\ReformasiBirokrasiController@forceDestroy',
        //     'as' => 'reformasi-birokrasi.force-destroy'
        // ]);
        Route::resource('profil', 'Backend\ProfilController');
        Route::put('profil/restore/{id}',[
            'uses' => 'Backend\ProfilController@restore',
            'as' => 'profil.restore'
        ]);
        Route::delete('profil/force-destroy/{id}',[
            'uses' => 'Backend\ProfilController@forceDestroy',
            'as' => 'profil.force-destroy'
        ]);
        Route::resource('galeri-foto', 'Backend\GaleriFotoController');
        Route::put('galeri-foto/restore/{id}',[
            'uses' => 'Backend\GaleriFotoController@restore',
            'as' => 'galeri-foto.restore'
        ]);
        Route::delete('galeri-foto/force-destroy/{id}',[
            'uses' => 'Backend\GaleriFotoController@forceDestroy',
            'as' => 'galeri-foto.force-destroy'
        ]);
        Route::resource('galeri-video', 'Backend\GaleriVideoController');
        Route::put('galeri-video/restore/{id}',[
            'uses' => 'Backend\GaleriVideoController@restore',
            'as' => 'galeri-video.restore'
        ]);
        Route::delete('galeri-video/force-destroy/{id}',[
            'uses' => 'Backend\GaleriVideoController@forceDestroy',
            'as' => 'galeri-video.force-destroy'
        ]);
        Route::resource('pengaduan', 'Backend\PengaduanController');
        Route::put('pengaduan/restore/{id}',[
            'uses' => 'Backend\PengaduanController@restore',
            'as' => 'pengaduan.restore'
        ]);
        Route::delete('pengaduan/force-destroy/{id}',[
            'uses' => 'Backend\PengaduanController@forceDestroy',
            'as' => 'pengaduan.force-destroy'
        ]);

        Route::resource('ppid', 'Backend\PpidController');
        Route::put('ppid/restore/{id}',[
            'uses' => 'Backend\PpidController@restore',
            'as' => 'ppid.restore'
        ]);
        
        Route::delete('ppid/force-destroy/{id}',[
            'uses' => 'Backend\PpidController@forceDestroy',
            'as' => 'ppid.force-destroy'
        ]);
        Route::get('info/{data}', [
            'uses'=>'Backend\InformasiController@index',
            'as'    => 'info.informasi',
        ]);
        Route::get('info-ppid/{data}', [
            'uses'=>'Backend\InformasiController@index',
            'as'    => 'info.informasi',
        ]);

        Route::resource('sikk', 'Backend\SikkController');
        Route::put('sikk/restore/{id}',[
            'uses' => 'Backend\SikkController@restore',
            'as' => 'sikk.restore'
        ]);
        Route::delete('sikk/force-destroy/{id}',[
            'uses' => 'Backend\SikkController@forceDestroy',
            'as' => 'sikk.force-destroy'
        ]);
        Route::resource('pmku', 'Backend\PmkuController');
        Route::put('pmku/restore/{id}',[
            'uses' => 'Backend\PmkuController@restore',
            'as' => 'pmku.restore'
        ]);
        Route::delete('pmku/force-destroy/{id}',[
            'uses' => 'Backend\PmkuController@forceDestroy',
            'as' => 'pmku.force-destroy'
        ]);
        Route::resource('pelaporan', 'Backend\PelaporanController');
        Route::put('pelaporan/restore/{id}',[
            'uses' => 'Backend\PelaporanController@restore',
            'as' => 'pelaporan.restore'
        ]);
        Route::delete('pelaporan/force-destroy/{id}',[
            'uses' => 'Backend\PelaporanController@forceDestroy',
            'as' => 'pelaporan.force-destroy'
        ]);
    });
    Route::group(['middleware'=>['role:superadmin|fasilitas|humas']], function(){
        Route::get('fasilitas/{data}', [
            'uses'=>'Backend\InformasiController@index',
            'as'    => 'info.informasi',
        ]);
        Route::resource('informasi', 'Backend\InformasiController');
        Route::put('informasi/restore/{id}',[
            'uses' => 'Backend\InformasiController@restore',
            'as' => 'informasi.restore'
        ]);
        Route::delete('informasi/force-destroy/{id}',[
            'uses' => 'Backend\InformasiController@forceDestroy',
            'as' => 'informasi.force-destroy'
        ]);
        // Route::resource('pelayanan', 'Backend\PelayananController');
        // Route::put('pelayanan/restore/{id}',[
        //     'uses' => 'Backend\PelayananController@restore',
        //     'as' => 'pelayanan.restore'
        // ]);
        // Route::delete('pelayanan/force-destroy/{id}',[
        //     'uses' => 'Backend\PelayananController@forceDestroy',
        //     'as' => 'pelayanan.force-destroy'
        // ]);

        /*-------------------pandawa----------------------*/
        Route::resource('soptu', 'Backend\SoptuController');
        Route::get('sop-tata-usaha', [
            'uses'=>'Backend\SoptuController@index',
            'as'    => 'sop.tu',
        ]);
        Route::put('soptu/restore/{id}',[
            'uses' => 'Backend\SoptuController@restore',
            'as' => 'soptu.restore'
        ]);
        Route::delete('soptu/force-destroy/{id}',[
            'uses' => 'Backend\SoptuController@forceDestroy',
            'as' => 'soptu.force-destroy'
        ]);

        Route::resource('soprenbang', 'Backend\SoprenbangController');
        Route::get('sop-rencana-pengembangan', [
            'uses'=>'Backend\SoprenbangController@index',
            'as'    => 'sop.renbang',
        ]);
        Route::put('soprenbang/restore/{id}',[
            'uses' => 'Backend\SoprenbangController@restore',
            'as' => 'soprenbang.restore'
        ]);
        Route::delete('soprenbang/force-destroy/{id}',[
            'uses' => 'Backend\SoprenbangController@forceDestroy',
            'as' => 'soprenbang.force-destroy'
        ]);

        Route::resource('soplala', 'Backend\SoplalaController');
        Route::get('sop-lalu-lintas', [
            'uses'=>'Backend\SoplalaController@index',
            'as'    => 'sop.lala',
        ]);
        Route::put('soplala/restore/{id}',[
            'uses' => 'Backend\SoplalaController@restore',
            'as' => 'soplala.restore'
        ]);
        Route::delete('soplala/force-destroy/{id}',[
            'uses' => 'Backend\SoplalaController@forceDestroy',
            'as' => 'soplala.force-destroy'
        ]);

        Route::resource('rapat-bidang', 'Backend\RapatBidangController');
        Route::get('rapat-bidang', [
            'uses'=>'Backend\RapatBidangController@index',
            'as'    => 'rapat-bidang',
        ]);
        Route::put('rapat-bidang/restore/{id}',[
            'uses' => 'Backend\RapatBidangController@restore',
            'as' => 'rapat-bidang.restore'
        ]);
        Route::delete('rapat-bidang/force-destroy/{id}',[
            'uses' => 'Backend\RapatBidangController@forceDestroy',
            'as' => 'rapat-bidang.force-destroy'
        ]);

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    protected $limit = 20;

        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
}

app/Http/Controllers/Backend/BeritaController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Model\Berita;
use Intervention\Image\Facades\Image;
use App\Http\Controllers\Backend\BackendController;
use App\Model\Tag;
use App\Http\Requests\Backend\BeritaStoreRequest;
use App\Http\Requests\Backend\BeritaUpdateRequest;
use Session;

class BeritaController extends BackendController
{

    public function __construct(){
      parent::__construct();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $onlyTrashed = FALSE;
        $perPage = $this->limit;

        if(($status = $request->get('status')) && $status == 'trash')
        {
          $posts = Berita::onlyTrashed()->with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::onlyTrashed()->count();
          $onlyTrashed = TRUE;
        }elseif($status=='published'){
          $posts = Berita::published()->with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::published()->count();
        }elseif($status=='scheduled'){
          $posts = Berita::scheduled()->with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::scheduled()->count();
        }elseif($status=='draft'){
          $posts = Berita::draft()->with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::draft()->count();
        }elseif($status=='own'){
          $posts = $request->user()->posts()->with('category','author')->latest()->paginate($this->limit);
          $postCount = $request->user()->posts()->count();
        }else{
          $posts = Berita::with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::count();
        }

        $statusList = $this->statusList($request);

        return view('backend.berita.index', compact('posts','postCount','onlyTrashed','statusList','perPage'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Berita $post)
    {
        $post = new Berita();
        return view('backend.berita.create',compact('post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BeritaStoreRequest $request)
    {
        $data = $this->handleRequest($request);
        // $request->user()->posts()->create($data);

        $newPost = $request->user()->posts()->create($data);

        $newPost->createTags($data['post_tags']);

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berita berhasil ditambahkan."
        ]);
        return redirect()->route('admin.berita.index');
    }

    private function handleRequest($request){
      $data = $request->all();
      $data['body'] = htmlspecialchars($data['body']);
      $bulan = date('m');
      $tahun = date('Y');

      if($request->hasFile('image')){
          $path = $request->file('image')->store('gambar-berita/'.$tahun.'/'.$bulan);
          $data['image'] = $path;
      }

      $data['slug'] = slugify($data['title']);
      $data['view_count'] = 1;

      return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Berita::findOrFail($id);
        return view('backend.berita.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BeritaUpdateRequest $request, $id)
    {
        $post = Berita::findOrFail($id);
        $oldImage = $post->image;

        $data = $this->handleRequest($request);
        $post->update($data);
        if($oldImage !== $post->image){
          $this->removeImage($oldImage);
        }
        $data['slug'] = slugify($data['title']);
        Session::flash("flash_notification", [
            "level" => "warning",
            "message" => "Berita berhasil diupdate."
        ]);

        return redirect()->route('admin.berita.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Berita::findOrFail($id)->delete();

        return redirect('/admin/berita')->with('trash-message', ['Berita sudah dihapus', $id]);
    }

    public function forceDestroy($id){
      $post = Berita::withTrashed()->findOrFail($id);
      $post->forceDelete();

      $this->removeImage($post->image);

      Session::flash("flash_notification", [
        "level" => "success",
        "message" => "Berita berhasil dihapus permanen."
    ]);

      return redirect('/admin/berita?status=trash');
    }

    public function restore($id)
    {
      $post = Berita::withTrashed()->findOrFail($id);
      $post->restore();

      Session::flash("flash_notification", [
        "level" => "warning",
        "message" => "Berita berhasil diaktifkan kembali."
    ]);

      return redirect('/admin/berita');

    }

    private function removeImage($image){
      if(!empty($image)){
          $imagePath = storage_path().'/app/'.$image;
          $ext = substr(strrchr($image,'.'),1);

        if(file_exists($imagePath)) unlink($imagePath);
      }
    }

    private function statusList($request){
      return [
        'own' => $request->user()->posts()->count(),
        'all' => Berita::count(),
        'published' => Berita::published()->count(),
        'scheduled' => Berita::scheduled()->count(),
        'draft' => Berita::draft()->count(),
        'trash' => Berita::onlyTrashed()->count(),
      ];
    }
}

resources/views/backend/informasi/create.blade.php
@extends('layouts.backend.main')
@section('pageTitle','Tambah Informasi')
@section('breadcrumbTitle','Tambah Informasi')
@section('breadcrumbParent','Pengaturan / Informasi')

@section('content')
	<div class="content-wrapper">
		@include('layouts.backend.breadcrumb')
		<!-- Main content -->
		    <div class="row">
		      <div class="col-lg-12">
		        {!! Form::model($informasi, [
		            'method' => 'POST',
		            'route' => 'admin.informasi.store',
								'id' => 'link-terkait-form',
								'files'=> TRUE,
		        ]) !!}

		        @include('backend.informasi.form')

		        {!! Form::close() !!}
		      </div>
		    </div>
		  <!-- ./row -->
	</div>
@endsection
@include('backend.informasi.script')

resources/views/backend/informasi/edit.blade.php
@extends('layouts.backend.main')
@section('pageTitle','Update Informasi')
@section('breadcrumbTitle','Update Informasi')
@section('breadcrumbParent','Pengaturan / Informasi')

@section('content')
	<div class="content-wrapper">
		@include('layouts.backend.breadcrumb')
		<!-- Main content -->
		    <div class="row">
		      <div class="col-lg-12">
		        {!! Form::model($informasi, [
		            'method' => 'PUT',
		            'route' => ['admin.informasi.update', $informasi->id],
		            'id' => 'link-terkait-form',
		            'files'=> TRUE,
		        ]) !!}

		        @include('backend.informasi.form')

		        {!! Form::close() !!}
		      </div>
		    </div>
		  <!-- ./row -->
	</div>
@endsection
@include('backend.informasi.script')

resources/views/backend/informasi/form.blade.php
<div class="wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title"><i class="fa fa-th"></i> Tambah Informasi</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <div class="card-body">
                  <div class="form-group {{ $errors->has('jenis_informasi_id') ? 'has-error' : ''}}">
                    {!! Form::label('Jenis Informasi') !!}

                    {!! Form::select('jenis_informasi_id', App\Model\JenisInformasi::pluck('nama','id'), null, ['class'=> 'js-selectize form-control','placeholder' => 'Pilih Jenis Informasi','name'=>'jenis_informasi_id']) !!}

                    @if($errors->has('jenis_informasi_id'))
                    <span class="help-block text-danger">{{ $errors->first('jenis_informasi_id') }}</span>
                    @endif
                  </div>

                  <div class="form-group {{ $errors->has('judul_informasi') ? 'has-error' : ''}} m-input">
                    {!! Form::label('Judul Informasi') !!}

                    {!! Form::text('judul_informasi', null, ['class'=> 'form-control']) !!}

                    @if($errors->has('judul_informasi'))
                    <span class="help-block label-danger">{{ $errors->first('judul_informasi') }}</span>
                    @endif
                  </div>

                  <div class="form-group {{ $errors->has('konten') ? 'has-error' : ''}} m-input">
                    {!! Form::label('Konten') !!}

                    {!! Form::textarea('konten', null, ['class'=> 'form-control','id'=>'summernote']) !!}

                    @if($errors->has('konten'))
                    <span class="help-block label-danger">{{ $errors->first('konten') }}</span>
                    @endif
                  </div>

                  <div class=" bulan form-group {{ $errors->has('bulan') ? 'has-error' : ''}}">
                    {!! Form::label('Bulan') !!}

                    {!! Form::select('bulan',App\Model\Bulan::pluck('nama','id'), null, ['class'=> 'js-selectize bulan form-control','placeholder' => 'Pilih Bulan (Opsional)']) !!}

                    @if($errors->has('bulan'))
                    <span class="help-block text-danger">{{ $errors->first('bulan') }}</span>
                    @endif
                  </div>

                  <div class="tahun form-group {{ $errors->has('tahun') ? 'has-error' : ''}}">
                    {!! Form::label('Tahun') !!}

                    {!! Form::select('tahun', App\Model\Tahun::pluck('tahun','id'), null, ['class'=> 'js-selectize tahun form-control','placeholder' => 'Pilih Tahun (Opsional)','id'=>'tahun']) !!}

                    @if($errors->has('tahun'))
                    <span class="help-block text-danger">{{ $errors->first('tahun') }}</span>
                    @endif
                  </div>

                  <div class="form-group {{ $errors->has('gambar') ? 'has-error' : ''}} m-input">
                    {!! Form::label('Gambar / Dokumen PDF') !!}
                    &nbsp;<br>
                    @if($informasi->gambar)
                      <?php
                          $path = $informasi->gambar;
                          $ext = pathinfo($path, PATHINFO_EXTENSION);
                      ?>
                      @if($ext == 'pdf')
                        <object type="application/pdf" data="{{ url($path) }}" width="50%" height="500" style="height: 85vh;" class="domisili">No Support</object><br><br>
                      @else 
                        <a href="{{ url($path) }}" target="_blank"><img src="{{ url($path) }}" width="50%"></a><br>
                      @endif
                    @else
                    @endif
  
                    {!! Form::file('gambar', null, ['class'=> 'form-control']) !!}
                    @if($errors->has('gambar'))
                    <span class="help-block label-danger">{{ $errors->first('gambar') }}</span>
                    @endif
                  </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-info"><i class="fa fa-save"></i>  {{ $informasi->exists ? 'Update' : 'Save'}}</button>
                  <a href="{{ route('admin.informasi.index') }}" class="btn btn-warning"><i class="fa fa-undo"></i> Cancel</a>
                </div>
            </div>
            <!-- /.card -->

          </div>
          <!--/.col (left) -->
          <!-- right column -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@include('backend.informasi.script')

resources/views/backend/informasi/index.blade.php
@extends('layouts.backend.main')
@section('pageTitle','Informasi')
@section('breadcrumb','Informasi')

@section('content')
	<div class="content-wrapper">
	@include('layouts.backend.breadcrumb')
	    <!-- Main content -->
	    <section class="content">
	      <div class="container-fluid">
	        <div class="row">
	          <div class="col-md-12">
	            <div class="card card-info">
	              <!-- /.card-header -->
	              <div class="card-header">
	                <h3 class="card-title">List Informasi</h3>
	                <div class="card-tools">
	                  
	                </div>
	              </div>
				  	

	              <!-- /.card-header -->
	              <div class="card-body p-1">
	              	<div class="row">
	              		<div class="col-md-12" style="padding-left: 10px; padding-right: 30px; padding-top: 10px; padding-bottom: 10px; ">
			                @include('backend.informasi.message')
			                @role('superadmin')
	              			<a href="{{ route('admin.informasi.create') }}" class="btn btn-info float-left">
	              			  <span>
	              			    <i class="fa fa-plus-circle"></i>
	              			    <span>
	              			      Tambah Informasi
	              			    </span>
	              			  </span>
	              			</a>
	              			<div class="float-right" style="color: blue;">
	              				<?php $links = [];?>
	              				@foreach($statusList as $key => $value)
	              				    @if($value)
	              				      <?php $selected = Request::get('status') == $key ? 'selected-status' : '' ?>
	              				      <?php $links[] = "<a class=\"{$selected}\" href=\"?status={$key}\">" .ucwords($key) ."({$value}) </a>"?>
	              				    @endif
	              				@endforeach
	              				{!! implode(' | ', $links) !!}
	              			</div>
	              			@endrole
	              		</div>
	              	</div>

	                @if(! $informasis->count())
	                  <div class="alert alert-danger">
	                    Data Tidak Ditemukan
	                  </div>
	                @else
	                    @if($onlyTrashed)
	                      @include('backend.informasi.table-trash')
	                    @else
	                      @include('backend.informasi.table')
	                    @endif
	                @endif
	              </div>
	              <!-- /.card-body -->
	              <div class="card-footer clearfix">
	                <div class="clearfix">
	                    {{ $informasis->appends( Request::query() )->render() }}
	                  </div>
	                  <div class="pull-right">
	                    <small>{{ $informasisCount }} {{ str_plural('Record', $informasisCount)}}</small>
	                  </div>
	              </div>

	            </div>
	            <!-- /.card -->
	          </div>

	        </div>
	        <!-- /.row -->
	      </div><!-- /.container-fluid -->
	    </section>
	    <!-- /.content -->
	  </div>
@endsection

resources/views/backend/informasi/js.blade.php
@section('script')
	<script type="text/javascript">
		$(document).ready(function(){
			$("select#bulan").hide();
			$('select#tahun').hide();
			$('#cke_konten').show();
			$("label[for='Konten']").show();

			$('select[name=jenisInformasi]').change(function() {
			    if (this.value == 4 || this.value == 7) {
			        $('#bulan').show();
			        $('#tahun').show();
			        $('#cke_konten').hide();
			        $("label[for='Konten']").hide();
			    }
			    else{
			        $('#bulan').hide();
			        $('#tahun').hide();
			        $('#cke_konten').show();
			        $("label[for='Konten']").show();
			    }
			});
		});
	</script>
@endsection

resources/views/backend/informasi/message.blade.php
@if(session('message'))
  <div class="alert alert-success">
    <span>{{ session('message') }}</span>
  </div>
@elseif(session('error-message'))
    <div class="alert alert-danger">
      {{ session('error-message') }}
    </div>
@elseif(session('trash-message'))
<?php list($message, $postId) = session('trash-message');?>
{!! Form::open(['method'=>'PUT', 'route' => ['admin.informasi.restore',$postId]]) !!}
<div class="alert alert-danger">
  {{ $message }}
    <button type="submit" class="btn btn-sm btn-warning"><i class="fa fa-undo"></i>   Undo</button>
</div>
{!! Form::close() !!}
@endif

resources/views/backend/informasi/table.blade.php
<table class="table table-striped">
  <tr>
    <th style="width: 10px">No</th>
    <th>Judul Informasi</th>
    <th class="text-center">Gambar</th>
    <th class="text-center">Aksi</th>
  </tr>
  <?php $no = paging_number($perPage);?>
  @foreach($informasis as $informasi)
    <tr>
      <td>{{ $no }}.</td>
      <td>{{ $informasi->judul_informasi }}</td>
      @if($informasi->gambar)
        <?php
            $path = $informasi->gambar;
            $ext = pathinfo($path, PATHINFO_EXTENSION);
        ?>
        @if($ext == 'pdf')
        <td align="center">
          <a href='{{ url($path) }}' class="btn btn-sm btn-info btn-block" title="View PDF" target="blank" ><i class="fa fa-eye"></i> View PDF</a>
          
          <!-- di tambahin tombol hapus di sini -->
          &nbsp;

          <a onclick="return confirm('Apakah Anda yakin untuk menghapus data?')" href="{{ route('admin.informasi.removeFile', $informasi->id) }}" class="btn btn-sm btn-danger btn-block" title="Move to Trash">
            <i class="fa fa-trash"></i> Hapus PDF
          </a>
        </td>
          @else 
                <td align="center"><a href="{{ url($path) }}" target="_blank"><img src="{{ url($path) }}" height="70px" /></a></td>
        @endif
      @else
        <td align="center"> - </td>
      @endif
      <td align="center">
        {!! Form::open(['method' => 'DELETE', 'route' => ['admin.informasi.destroy', $informasi->id]]) !!}
        <a href="{{ route('admin.informasi.edit', $informasi->id) }}" class="btn btn-sm btn-warning btn-block" title="Edit">
          <i class="fa fa-edit text-black"></i> Edit
        </a>
          @role('superadmin')
          <button onclick="return confirm('Apakah Anda yakin untuk menghapus data?')" type="submit" class="btn btn-sm btn-danger btn-block" title="Move to Trash">
            <i class="fa fa-trash"></i> Hapus
          </button>
          @endrole
        {!! Form::close() !!}
      </td>
    </tr>
    <?php $no++;?>
  @endforeach
</table>