routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*-----------------index-----------------------*/
Auth::routes(['verify'=>true]);
Route::match(['get', 'post'], 'register', function(){
    return redirect('/');
});

Route::get('kirim-email',[
    'uses' => 'TestController@kirim',
    'as'    => 'kirim'
]);

Route::get('/home',[
    'uses'  => 'HomeController@index',
    'as'    => 'home' ,
    'middleware' => ['role:superadmin|keuangan|kepegawaian|humas|renpro|desain|tarif|lala|fasilitas|bimus']
]);

Route::get('/verifikasi-sukses','HomeController@verifikasi');
/*--------------------end of index-------------*/

/*-------------------backend-------------------*/
Route::group(['prefix'=>'admin', 'middleware'=>['auth'],'as'=>'admin.'], function(){
    Route::group(['middleware'=>['role:superadmin|humas']], function(){
        Route::resource('kategori-berita', 'Backend\KategoriBeritaController');
        Route::resource('kategori-foto', 'Backend\KategoriFotoController');
        Route::resource('kategori-video', 'Backend\KategoriVideoController');
        Route::resource('kategori-hukum', 'Backend\KategoriHukumController');
        Route::resource('jenis-usaha', 'Backend\JenisUsahaController');
        Route::resource('jenis-pelayanan', 'Backend\JenisPelayananController');
        Route::resource('jenis-informasi', 'Backend\JenisInformasiController');
        Route::resource('jenis-laporan', 'Backend\JenisLaporanController');
        Route::resource('tampilan-depan', 'Backend\TampilanDepanController');
        Route::resource('berita', 'Backend\BeritaController');
        Route::put('berita/restore/{id}',[
            'uses' => 'Backend\BeritaController@restore',
            'as' => 'berita.restore'
        ]);
        Route::delete('berita/force-destroy/{id}',[
            'uses' => 'Backend\BeritaController@forceDestroy',
            'as' => 'berita.force-destroy'
        ]);
        Route::resource('link-terkait', 'Backend\LinkTerkaitController');
        Route::put('link-terkait/restore/{id}',[
            'uses' => 'Backend\LinkTerkaitController@restore',
            'as' => 'link-terkait.restore'
        ]);
        Route::delete('link-terkait/force-destroy/{id}',[
            'uses' => 'Backend\LinkTerkaitController@forceDestroy',
            'as' => 'link-terkait.force-destroy'
        ]);
        // Route::resource('reformasi-birokrasi', 'Backend\ReformasiBirokrasiController');
        // Route::put('reformasi-birokrasi/restore/{id}',[
        //     'uses' => 'Backend\ReformasiBirokrasiController@restore',
        //     'as' => 'reformasi-birokrasi.restore'
        // ]);
        // Route::delete('reformasi-birokrasi/force-destroy/{id}',[
        //     'uses' => 'Backend\ReformasiBirokrasiController@forceDestroy',
        //     'as' => 'reformasi-birokrasi.force-destroy'
        // ]);
        Route::resource('profil', 'Backend\ProfilController');
        Route::put('profil/restore/{id}',[
            'uses' => 'Backend\ProfilController@restore',
            'as' => 'profil.restore'
        ]);
        Route::delete('profil/force-destroy/{id}',[
            'uses' => 'Backend\ProfilController@forceDestroy',
            'as' => 'profil.force-destroy'
        ]);
        Route::resource('galeri-foto', 'Backend\GaleriFotoController');
        Route::put('galeri-foto/restore/{id}',[
            'uses' => 'Backend\GaleriFotoController@restore',
            'as' => 'galeri-foto.restore'
        ]);
        Route::delete('galeri-foto/force-destroy/{id}',[
            'uses' => 'Backend\GaleriFotoController@forceDestroy',
            'as' => 'galeri-foto.force-destroy'
        ]);
        Route::resource('galeri-video', 'Backend\GaleriVideoController');
        Route::put('galeri-video/restore/{id}',[
            'uses' => 'Backend\GaleriVideoController@restore',
            'as' => 'galeri-video.restore'
        ]);
        Route::delete('galeri-video/force-destroy/{id}',[
            'uses' => 'Backend\GaleriVideoController@forceDestroy',
            'as' => 'galeri-video.force-destroy'
        ]);
        Route::resource('pengaduan', 'Backend\PengaduanController');
        Route::put('pengaduan/restore/{id}',[
            'uses' => 'Backend\PengaduanController@restore',
            'as' => 'pengaduan.restore'
        ]);
        Route::delete('pengaduan/force-destroy/{id}',[
            'uses' => 'Backend\PengaduanController@forceDestroy',
            'as' => 'pengaduan.force-destroy'
        ]);

        Route::resource('ppid', 'Backend\PpidController');
        Route::put('ppid/restore/{id}',[
            'uses' => 'Backend\PpidController@restore',
            'as' => 'ppid.restore'
        ]);
        
        Route::delete('ppid/force-destroy/{id}',[
            'uses' => 'Backend\PpidController@forceDestroy',
            'as' => 'ppid.force-destroy'
        ]);
        Route::get('info/{data}', [
            'uses'=>'Backend\InformasiController@index',
            'as'    => 'info.informasi',
        ]);
        Route::get('info-ppid/{data}', [
            'uses'=>'Backend\InformasiController@index',
            'as'    => 'info.informasi',
        ]);

        Route::resource('sikk', 'Backend\SikkController');
        Route::put('sikk/restore/{id}',[
            'uses' => 'Backend\SikkController@restore',
            'as' => 'sikk.restore'
        ]);
        Route::delete('sikk/force-destroy/{id}',[
            'uses' => 'Backend\SikkController@forceDestroy',
            'as' => 'sikk.force-destroy'
        ]);
        Route::resource('pmku', 'Backend\PmkuController');
        Route::put('pmku/restore/{id}',[
            'uses' => 'Backend\PmkuController@restore',
            'as' => 'pmku.restore'
        ]);
        Route::delete('pmku/force-destroy/{id}',[
            'uses' => 'Backend\PmkuController@forceDestroy',
            'as' => 'pmku.force-destroy'
        ]);
        Route::resource('pelaporan', 'Backend\PelaporanController');
        Route::put('pelaporan/restore/{id}',[
            'uses' => 'Backend\PelaporanController@restore',
            'as' => 'pelaporan.restore'
        ]);
        Route::delete('pelaporan/force-destroy/{id}',[
            'uses' => 'Backend\PelaporanController@forceDestroy',
            'as' => 'pelaporan.force-destroy'
        ]);
    });
    Route::group(['middleware'=>['role:superadmin|fasilitas|humas']], function(){
        Route::get('fasilitas/{data}', [
            'uses'=>'Backend\InformasiController@index',
            'as'    => 'info.informasi',
        ]);
        Route::resource('informasi', 'Backend\InformasiController');
        Route::put('informasi/restore/{id}',[
            'uses' => 'Backend\InformasiController@restore',
            'as' => 'informasi.restore'
        ]);
        Route::delete('informasi/force-destroy/{id}',[
            'uses' => 'Backend\InformasiController@forceDestroy',
            'as' => 'informasi.force-destroy'
        ]);
        // Route::resource('pelayanan', 'Backend\PelayananController');
        // Route::put('pelayanan/restore/{id}',[
        //     'uses' => 'Backend\PelayananController@restore',
        //     'as' => 'pelayanan.restore'
        // ]);
        // Route::delete('pelayanan/force-destroy/{id}',[
        //     'uses' => 'Backend\PelayananController@forceDestroy',
        //     'as' => 'pelayanan.force-destroy'
        // ]);

        /*-------------------pandawa----------------------*/
        Route::resource('soptu', 'Backend\SoptuController');
        Route::get('sop-tata-usaha', [
            'uses'=>'Backend\SoptuController@index',
            'as'    => 'sop.tu',
        ]);
        Route::put('soptu/restore/{id}',[
            'uses' => 'Backend\SoptuController@restore',
            'as' => 'soptu.restore'
        ]);
        Route::delete('soptu/force-destroy/{id}',[
            'uses' => 'Backend\SoptuController@forceDestroy',
            'as' => 'soptu.force-destroy'
        ]);

        Route::resource('soprenbang', 'Backend\SoprenbangController');
        Route::get('sop-rencana-pengembangan', [
            'uses'=>'Backend\SoprenbangController@index',
            'as'    => 'sop.renbang',
        ]);
        Route::put('soprenbang/restore/{id}',[
            'uses' => 'Backend\SoprenbangController@restore',
            'as' => 'soprenbang.restore'
        ]);
        Route::delete('soprenbang/force-destroy/{id}',[
            'uses' => 'Backend\SoprenbangController@forceDestroy',
            'as' => 'soprenbang.force-destroy'
        ]);

        Route::resource('soplala', 'Backend\SoplalaController');
        Route::get('sop-lalu-lintas', [
            'uses'=>'Backend\SoplalaController@index',
            'as'    => 'sop.lala',
        ]);
        Route::put('soplala/restore/{id}',[
            'uses' => 'Backend\SoplalaController@restore',
            'as' => 'soplala.restore'
        ]);
        Route::delete('soplala/force-destroy/{id}',[
            'uses' => 'Backend\SoplalaController@forceDestroy',
            'as' => 'soplala.force-destroy'
        ]);

        Route::resource('rapat-bidang', 'Backend\RapatBidangController');
        Route::get('rapat-bidang', [
            'uses'=>'Backend\RapatBidangController@index',
            'as'    => 'rapat-bidang',
        ]);
        Route::put('rapat-bidang/restore/{id}',[
            'uses' => 'Backend\RapatBidangController@restore',
            'as' => 'rapat-bidang.restore'
        ]);
        Route::delete('rapat-bidang/force-destroy/{id}',[
            'uses' => 'Backend\RapatBidangController@forceDestroy',
            'as' => 'rapat-bidang.force-destroy'
        ]);

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    protected $limit = 20;

        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
}

app/Http/Controllers/Backend/BeritaController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Model\Berita;
use Intervention\Image\Facades\Image;
use App\Http\Controllers\Backend\BackendController;
use App\Model\Tag;
use App\Http\Requests\Backend\BeritaStoreRequest;
use App\Http\Requests\Backend\BeritaUpdateRequest;
use Session;

class BeritaController extends BackendController
{

    public function __construct(){
      parent::__construct();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $onlyTrashed = FALSE;
        $perPage = $this->limit;

        if(($status = $request->get('status')) && $status == 'trash')
        {
          $posts = Berita::onlyTrashed()->with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::onlyTrashed()->count();
          $onlyTrashed = TRUE;
        }elseif($status=='published'){
          $posts = Berita::published()->with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::published()->count();
        }elseif($status=='scheduled'){
          $posts = Berita::scheduled()->with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::scheduled()->count();
        }elseif($status=='draft'){
          $posts = Berita::draft()->with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::draft()->count();
        }elseif($status=='own'){
          $posts = $request->user()->posts()->with('category','author')->latest()->paginate($this->limit);
          $postCount = $request->user()->posts()->count();
        }else{
          $posts = Berita::with('category','author')->latest()->paginate($this->limit);
          $postCount = Berita::count();
        }

        $statusList = $this->statusList($request);

        return view('backend.berita.index', compact('posts','postCount','onlyTrashed','statusList','perPage'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Berita $post)
    {
        $post = new Berita();
        return view('backend.berita.create',compact('post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BeritaStoreRequest $request)
    {
        $data = $this->handleRequest($request);
        // $request->user()->posts()->create($data);

        $newPost = $request->user()->posts()->create($data);

        $newPost->createTags($data['post_tags']);

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berita berhasil ditambahkan."
        ]);
        return redirect()->route('admin.berita.index');
    }

    private function handleRequest($request){
      $data = $request->all();
      $data['body'] = htmlspecialchars($data['body']);
      $bulan = date('m');
      $tahun = date('Y');

      if($request->hasFile('image')){
          $path = $request->file('image')->store('gambar-berita/'.$tahun.'/'.$bulan);
          $data['image'] = $path;
      }

      $data['slug'] = slugify($data['title']);
      $data['view_count'] = 1;

      return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Berita::findOrFail($id);
        return view('backend.berita.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BeritaUpdateRequest $request, $id)
    {
        $post = Berita::findOrFail($id);
        $oldImage = $post->image;

        $data = $this->handleRequest($request);
        $post->update($data);
        if($oldImage !== $post->image){
          $this->removeImage($oldImage);
        }
        $data['slug'] = slugify($data['title']);
        Session::flash("flash_notification", [
            "level" => "warning",
            "message" => "Berita berhasil diupdate."
        ]);

        return redirect()->route('admin.berita.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Berita::findOrFail($id)->delete();

        return redirect('/admin/berita')->with('trash-message', ['Berita sudah dihapus', $id]);
    }

    public function forceDestroy($id){
      $post = Berita::withTrashed()->findOrFail($id);
      $post->forceDelete();

      $this->removeImage($post->image);

      Session::flash("flash_notification", [
        "level" => "success",
        "message" => "Berita berhasil dihapus permanen."
    ]);

      return redirect('/admin/berita?status=trash');
    }

    public function restore($id)
    {
      $post = Berita::withTrashed()->findOrFail($id);
      $post->restore();

      Session::flash("flash_notification", [
        "level" => "warning",
        "message" => "Berita berhasil diaktifkan kembali."
    ]);

      return redirect('/admin/berita');

    }

    private function removeImage($image){
      if(!empty($image)){
          $imagePath = storage_path().'/app/'.$image;
          $ext = substr(strrchr($image,'.'),1);

        if(file_exists($imagePath)) unlink($imagePath);
      }
    }

    private function statusList($request){
      return [
        'own' => $request->user()->posts()->count(),
        'all' => Berita::count(),
        'published' => Berita::published()->count(),
        'scheduled' => Berita::scheduled()->count(),
        'draft' => Berita::draft()->count(),
        'trash' => Berita::onlyTrashed()->count(),
      ];
    }
}

resources/views/backend/jenis-laporan/_form.blade.php
<div class="form-group{{ $errors->has('kode') ? ' is-invalid' : '' }}">
{!! Form::label('Kode Laporan') !!} 
<?php
    if($errors->has('kode')){
        $invalid = 'form-control is-invalid';
    }else{
        $invalid = 'form-control';
    }
?>
{!! Form::text('kode', null, ['class'=>$invalid, 'placeholder' => 'Kode Laporan']) !!}
{!! $errors->first('kode', '<p class="invalid-feedback">:message</p>') !!}
</div>

<div class="form-group{{ $errors->has('nama') ? ' is-invalid' : '' }}">
{!! Form::label('Nama Laporan') !!} 
<?php
    if($errors->has('nama')){
        $invalid = 'form-control is-invalid';
    }else{
        $invalid = 'form-control';
    }
?>
{!! Form::text('nama', null, ['class'=>$invalid, 'placeholder' => 'Nama Laporan']) !!}
{!! $errors->first('nama', '<p class="invalid-feedback">:message</p>') !!}
</div>

<div class="form-group{{ $errors->has('keterangan') ? ' is-invalid' : '' }}">
{!! Form::label('Keterangan Laporan') !!} 
<?php
    if($errors->has('keterangan')){
        $invalid = 'form-control is-invalid';
    }else{
        $invalid = 'form-control';
    }
?>
{!! Form::textarea('keterangan', null, ['class'=> 'form-control','rows'=>8, 'placeholder' => '']) !!}
{!! $errors->first('keterangan', '<p class="invalid-feedback">:message</p>') !!}
</div>

{!! Form::submit('Simpan', ['class'=>'btn btn-info']) !!}

resources/views/backend/jenis-laporan/create.blade.php
@extends('layouts.backend.main')
@section('breadcrumb','Tambah Jenis Laporan')
@section('content')
        <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        @include('layouts.backend.breadcrumb')
    
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/admin/jenis-laporan') }}">Pengaturan Jenis Laporan</a></li>
                            <li class="breadcrumb-item"> Jenis Laporan</li>
                            <li class="breadcrumb-item active"> Tambah Jenis Laporan</li>
                        </ol>
                        <div class="card border-primary mb-3 card-info">
                        <div class="card-header">Tambah Jenis Laporan</div>
                            <div class="card-body">
                                {!! Form::open([
                                    'url'       => route('admin.jenis-laporan.store'),
                                    'method'    => 'post',
                                    'class'     => 'form-horizontal' 
                                ]) !!}
                                
                                @include('backend.jenis-laporan._form')
            
                                {!! Form::close() !!}
                            </div>
                        </div>
                </div>
            </div>
    
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
@endsection

resources/views/backend/jenis-laporan/edit.blade.php
@extends('layouts.backend.main')
@section('title','Edit Jenis Laporan')
@section('breadcrumb','Edit Jenis Laporan')
@section('content')
        <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        @include('layouts.backend.breadcrumb')
    
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/admin/jenis-laporan') }}">Pengaturan Jenis Laporan</a></li>
                            <li class="breadcrumb-item"> Jenis Laporan</li>
                            <li class="breadcrumb-item active"> Edit Jenis Laporan</li>
                        </ol>
                        <div class="card border-primary mb-3 card-info">
                        <div class="card-header">Edit Jenis Laporan</div>
                            <div class="card-body">
                                {!! Form::model($jenisLaporan,[
                                    'url'       => route('admin.jenis-laporan.update', $jenisLaporan->id),
                                    'method'    => 'put',
                                    'class'     => 'form-horizontal' 
                                ]) !!}
                                
                                @include('backend.jenis-laporan._form')
            
                                {!! Form::close() !!}
                            </div>
                        </div>
                </div>
            </div>
    
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
@endsection

resources/views/backend/jenis-laporan/index.blade.php
@extends('layouts.backend.main')
@section('breadcrumb','Jenis Laporan')
@section('content')
        <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        @include('layouts.backend.breadcrumb')
        @include('layouts._flash')
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/home') }}">Pengaturan Jenis Laporan</a></li>
                            <li class="breadcrumb-item active"> Jenis Laporan</li>
                        </ol>
                        <div class="card border-primary mb-3 card-info">
                        <div class="card-header">Daftar Jenis Laporan</div>
                        <div class="card-body">
                        <p><a href="{{ route('admin.jenis-laporan.create') }}" class="btn btn-outline-info"><span><i class="fa fa-plus-circle"></i></span> Tambah Jenis Laporan</a></p>
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Kode Jenis Laporan</th>
                                        <th>Nama</th>
                                        <th>Keterangan</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                        </div>
                </div>
            </div>
    
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
@endsection
@section('script')
<script>
    $(function(){
        $('table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('admin.jenis-laporan.data') !!}',
            columns: [
                { data: 'kode', name: 'kode' },
                { data: 'nama', name: 'nama' },
                { data: 'keterangan', name: 'keterangan' },
                { data: 'action', name: 'action', searchable: false, orderable: false }
            ],
        });
    });
</script>
@endsection

resources/views/backend/jenis-laporan/script.blade.php
@section('script')
  <script type="text/javascript">
    $('#title').on('blur',function(){
      var theTitle = this.value.toLowerCase().trim(),
        slugInput = $('#slug'),
        theSlug = theTitle.replace(/&/g, '-and-')
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/\-\-+/g, '-')
            .replace(/^-+|-+$/g, '');

      slugInput.val(theSlug);
    });

    $('.js-selectize').selectize({
      sortField: 'text'
    });

    $('.input-tags').selectize({
    delimiter: ',',
    persist: false,
    create: function(input) {
        return {
            value: input,
            text: input
        }
    }
    });
  </script>
@endsection